### PR TITLE
Adding SSL Option to Docker RUN command

### PR DESCRIPTION
**Pull request by JulianHn**
This PR adds the --ssl option to the Docker RUN command in the `docker/HIK` Dockerfile.

This should allow to expose imswitch in the docker via plain HTTP, which is necessary for easy deployment behind SSL terminating reverse proxies. Otherwise we would need to import all of the self-signed certs into the proxy which do not survive container restarts.

### CODE REVIEW

**Comment by beniroquai** [comment]
Ah, thanks. Would I need to forward any other port or is the `-ssl` option sufficient? It would be important to access port 8001 through this website (SSL is necessary to access a non-localhost webserver with the self-signed certificate..) https://youseetoo.github.io/imswitch/index.html

Thanks again!

**Comment by beniroquai** [comment]
The `ssl` option is needed to run python, is this right? Or would I need to start the container with this flag?

**Comment by JulianHn** [comment]
So ... I have to admit my PR until now was poorly tested.
I found out, that the `--headless` and `--ssl` options were not actually working as you probably intended, which should now hopefully be fixed in `imswitch/__main__.py`

I have also changed the Dockerfile with some basic refactoring with so that it **should** hopefully now do what I think it should.
HOWEVER: This is fully untested as the Dockerfile depends on the github repo, so changes cannot actually be tested inside Docker.

I will open a separate issue to discuss some general changes to the repo layout wrt to Docker, that should hopefully make building and developing using the docker containers easier.

**Comment by beniroquai** [comment]
Ah, I think now I understood what you meant. Yup, you cought me. Non-programmer at work here.. @jacopoabramo can tell you stories ;-) 

For installing everything e.g. on a raspi, I generated this bash script(s): https://github.com/openUC2/ImSwitchDockerInstall 
Not sure if this helps. I documented some portions of it here: https://openuc2.github.io/docs/ImSwitch/ImSwitchDocker/

**Comment by beniroquai** [comment]
Will test the PR and merge it. There was a reason why I didn't move everything to the seperate `.sh`-file, but maybe that was mostly due to my stubidity. It has to compile inside the GH actions for the package-stuff.

**Comment by beniroquai** [comment]
Works for now (at least it compiles).

**Pull request merged**
