### PR TITLE
Add services for chatbot

### PR DESCRIPTION
**Pull request by oeway**
This PR integrates the logic for controlling microscope to the imswitch server (instead of the chatbot client).

### CODE REVIEW

**Review by beniroquai — APPROVED** [review]

**Comment by oeway** [comment]
Hi @beniroquai this is just a quick fix, actually, I think you can move most of the logic into the imswitch server, see the updated docs here: https://github.com/bioimage-io/bioimageio-chatbot/blob/main/docs/development.md
 ( use the hypha approach instead of ImJoy) 

Could you give a shot?

**Comment by beniroquai** [comment]
@oeway thanks for your help. When using a simple remote service like the one below and logging in into the chatbot, I get the following error:


```js
chat?extension=V3JuN…RG:my-extension:915 Failed to connect to extension service: V3JuNHof7gUNzmUtCSZYan/U2yckzkGxhrY3NkVRXSNRG:my-extension Error: Traceback (most recent call last):
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/imjoy_rpc/hypha/rpc.py", line 864, in _wait
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hypha/core/workspace.py", line 751, in get_service
    service_api = await rpc.get_remote_service(service_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/imjoy_rpc/hypha/rpc.py", line 425, in get_remote_service
    svc = await asyncio.wait_for(method(service_id), timeout=timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
    at V._decode (rpc.js:1406:19)
    at V._decode (rpc.js:1488:35)
    at V._handle_method (rpc.js:1013:27)
    at V._fire (utils.js:353:11)
    at V._on_message (rpc.js:371:12)
    at i.onmessage (websocket-client.js:55:14)
﻿```

with this service 
```py
import asyncio
from imjoy_rpc.hypha import connect_to_server, login

def get_schema():
    return {
        "my_tool": {
            "type": "object",
            "properties": {
                "my_param": {
                    "type": "number",
                    "description": "This is my parameter"
                }
            }
        }
    }

def my_tool(config):
    print(config["my_param"])
    return {"result": "success"}

chatbot_extension = {
    "id": "my-extension",
    "type": "bioimageio-chatbot-extension",
    "name": "My Extension",
    "description": "This is my extension",
    "get_schema": get_schema,
    "tools": {
        "my_tool": my_tool
    }
}

async def register_extension():
    server_url = "https://chat.bioimage.io"
    try:
        server = await connect_to_server({"server_url": server_url})
        svc = await server.register_service(chatbot_extension)
        print(f"Extension service registered with id: {svc.id}, you can visit the service at: {server_url}/public/apps/bioimageio-chatbot-client/chat?extension={svc.id}")
    except Exception as e:
        print(f"Failed to register extension: {e}")

# Run the async function using asyncio
if __name__ == "__main__":
    asyncio.run(register_extension())
    input() # keep extension alive?
```

The service is not registered:

image


Any idea what'S going on? The remote python file does not throw any errors.

**Comment by beniroquai** [comment]
It takes relatively long until the message is thrown. Is there any chance to check the server connection with a ping? Might be a firewall issue. It used to work before though. 

image

**Comment by beniroquai** [comment]
It seems that the oauth is timing out? I cleared cookies, but this didn't change anything.

**Comment by beniroquai** [comment]
One more update. Tried a different computer on a different network. This time I had to enter a code:
image

I think this is new - but no success either. It times out.

**Comment by oeway** [comment]
Hi, by default the service is private so the chatbot cannot access it. To fix it, you can either login when you register the service in imswitch, or make the service public.

## Option 1: login with the same user
```python
import asyncio
from imjoy_rpc.hypha import connect_to_server, login
token = await login({"server_url": server_url})
server = await connect_to_server({"server_url": server_url, "token": token})
```
## Option 2: set the service public
```python
chatbot_extension["config"] = {"visibility": "public"}
```

For public service, you can also add authorization, e.g. to allow only some users by their emails etc. see https://ha.amun.ai/#/?id=service-authorization

## Additional notes

While trying I also noticed that the `get_schema` need to be fixed as follows, it misses "title" and "description" for the tool:
```python
def get_schema():
    return {
        "my_tool": {
            "type": "object",
            "title": "my_tool",
            "description": "my tool",
            "properties": {
                "my_param": {
                    "type": "number",
                    "description": "This is my parameter"
                }
            }
        }
    }

def my_tool(config):
    print(config["my_param"])
    return {"result": "success"}

```

Also to keep the service running, instead of using `input()`, you should do the following:
```python
import asyncio

loop = asyncio.get_event_loop()
loop.create_task(register_extension())
loop.run_forever()
```

**Comment by oeway** [comment]
> ```python
> token = await login({"server_url": server_url})
> ```

You need to login twice, one for the imswitch server: 
```
# a link will be printed in your console, you can also display it in the interface as you done before
token = await login({"server_url": server_url})
```

Then you need to also login in the chatbot using the same user.

The other approach is to make the service public.

**Comment by beniroquai** [comment]
yup, that works! Brilliant. Thanks a lot. I will proceed to add this to the imswitchserver and ask melmin to do some magic ;)

**Comment by beniroquai** [comment]
Btw. there were many many people asking for our technique yesterday during the poster session 
https://figshare.com/articles/poster/Poster_Focus_on_Microcsopy_Genoa_2024_Democratizing_Smart-Microscopy_using_ImSwitch_and_UC2_/25444054

**Comment by beniroquai** [comment]
Hey @oeway I'm continueing to experiment with the code. I have the following code to expose some of the functions of a microscope (probably completely wrong). I wasn't sure how to link the schemas to the tools as this wasn't mentioned in the docs yet. 


current code that I'm about to paste into the hyphacontroller:
```py
import asyncio
from imjoy_rpc.hypha import connect_to_server, login


def get_schema():
    return {
        "UC2_microscope": {
            "type": "object",
            "title": "UC2_microscope",
            "description": "An adapter to control the stage, laser, illumination of the UC2 microscope and readout frames.",
            "properties": {
                "x_coordinate": {
                    "type": "number",
                    "description": "Move the stage along X axis in relative physical coordinates."
                },
                "y_coordinate": {
                    "type": "number",
                    "description": "Move the stage along Y axis in relative physical coordinates."
                },
                "z_coordinate": {
                    "type": "number",
                    "description": "Move the stage along Z axis in relative physical coordinates."
                }, 
                "laser_1":{
                    "type": "number",
                    "description": "Set the power of laser 1."
                },
                "laser_2":{
                    "type": "number",
                    "description": "Set the power of laser 2."
                },
                "illumination":{
                    "type": "number",
                    "description": "Set the power of the illumination."
                },
                "snap_image":{  
                    "type": "boolean",
                    "description": "Capture an image."
                }
            }
        }
    }

def move_stage_x(config):
    print(config["x_coordinate"])
    return {"result": "success"}

def move_stage_y(config):
    print(config["y_coordinate"])
    return {"result": "success"}

def move_stage_z(config):
    print(config["z_coordinate"])
    return {"result": "success"}

def set_laser_1(config):
    print(config["laser_1"])
    return {"result": "success"}

def set_laser_2(config):
    print(config["laser_2"])
    return {"result": "success"}

def set_illumination(config):
    print(config["illumination"])
    return {"result": "success"}

def snap_image(config):
    print(config["snap_image"])
    import numpy as np
    mImage = np.random.rand(512, 512)
    return {"result": "success", "image": mImage}
    
def microscope(config):
    print(config)
    return {"result": "success"}

chatbot_extension = {
    "id": "UC2_microscope",
    "type": "bioimageio-chatbot-extension",
    "name": "UC2 Control Microscope",
    "description": "This exkension allows you to control the UC2 microscope, capture images, move the stage and turn on/off illumination.",
    "get_schema": get_schema,
    "tools": {
        "x_coordinate": move_stage_x,
        "y_coordinate": move_stage_y,
        "z_coordinate": move_stage_z,
        "laser_1": set_laser_1,
        "laser_2": set_laser_2,
        "illumination": set_illumination,
        "snap_image": snap_image,
        "microscope": microscope
    }
}

async def register_extension():
    server_url = "https://chat.bioimage.io"
    try:
        import asyncio
        from imjoy_rpc.hypha import connect_to_server, login
        token = await login({"server_url": server_url})
        server = await connect_to_server({"server_url": server_url, "token": token})
        svc = await server.register_service(chatbot_extension)
        print(f"Extension service registered with id: {svc.id}, you can visit the service at: {server_url}/public/apps/bioimageio-chatbot-client/chat?extension={svc.id}")
    except Exception as e:
        print(f"Failed to register extension: {e}")

# Run the async function using asyncio
import asyncio
loop = asyncio.get_event_loop()
loop.create_task(register_extension())
loop.run_forever()
```

The error in the chatbot window:
```py
Error: The server failed to respond, please try again. Error: Traceback (most recent call last):
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bioimageio_chatbot/chatbot.py", line 393, in chat
    return await talk_to_assistant(assistant_name, session_id, m, status_callback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bioimageio_chatbot/chatbot.py", line 341, in talk_to_assistant
    raise e
  File "/usr/local/lib/python3.11/site-packages/bioimageio_chatbot/chatbot.py", line 334, in talk_to_assistant
    response = await assistant.handle(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/schema_agents/role.py", line 292, in handle
    responses = await asyncio.gather(*responses)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/schema_agents/role.py", line 252, in _run_action
    return await action(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bioimageio_chatbot/chatbot.py", line 109, in respond_to_user
    ts = await extension_to_tools(extension)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bioimageio_chatbot/chatbot_extensions/__init__.py", line 54, in extension_to_tools
    assert k in extension.tools, f"Tool `{k}` not found in extension `{extension.id}`."
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: Tool `UC2_microscope` not found in extension `UC2_microscope`.
```

**Comment by oeway** [comment]
The issue is in the `get_schema`, it should return a dictionary with keys correspond to the `tools`. And you can combine the move stage into one function as a tool, see below:
```python
import asyncio
from imjoy_rpc.hypha import connect_to_server, login

def move_stage(config):
    print(config["x"], config["y"], config["z"])
    return {"result": "success"}

def get_schema():
    return {
        "move_stage": {
            "type": "object",
            "title": "MoveStage",
            "description": "Move the microscope stage",
            "properties": {
                "x": {
                    "type": "number",
                    "description": "Move the stage along X axis in relative physical coordinates."
                },
                "y": {
                    "type": "number",
                    "description": "Move the stage along Y axis in relative physical coordinates."
                },
                "z": {
                    "type": "number",
                    "description": "Move the stage along Z axis in relative physical coordinates."
                }
            }
        },
       # "snap_image": ...
    }

chatbot_extension = {
    "id": "UC2_microscope",
    "type": "bioimageio-chatbot-extension",
    "name": "UC2 Control Microscope",
    "description": "This exkension allows you to control the UC2 microscope, capture images, move the stage and turn on/off illumination.",
    "get_schema": get_schema,
    "tools": {
        "move_stage": move_stage,
        # "snap_image": ...
    }
}
```

**Comment by beniroquai** [comment]
Ay. Will try. thanks!

**Comment by oeway** [comment]
> Ay. Will try. thanks!

The docs here are up to date: https://github.com/bioimage-io/bioimageio-chatbot/blob/main/docs/development.md

**Comment by beniroquai** [comment]
Perfect. Thanks.

Next question: Serializing the numpy image would be best via base64 or what do you typically use? Or is this not intended to do it that way:

```py
def snap_image(config):
    print(config["snap"])
    mImage = np.random.rand(512, 512)
    # return the image as a base64 encoded string
    import base64
    import io
    import matplotlib.pyplot as plt
    buf = io.BytesIO()
    plt.imsave(buf, mImage, cmap='gray')
    buf.seek(0)
    mImage = base64.b64encode(buf.read()).decode('utf-8')
    return {"result": "success", "image": mImage}
```

I'm wondering how i could reuse/recycle the code here https://github.com/openUC2/ImSwitch/blob/master/imswitch/imcontrol/controller/controllers/HyphaController.py#L352 to use it inside your extension framework.

**Comment by oeway** [comment]
> Perfect. Thanks.
> 
> Next question: Serializing the numpy image would be best via base64 or what do you typically use? 
> I'm wondering how i could reuse/recycle the code here https://github.com/openUC2/ImSwitch/blob/master/imswitch/imcontrol/controller/controllers/HyphaController.py#L352 to use it inside your extension framework.

Hi, you should not return the image to the chatbot, instead, save it to your disk and return a path for example, the chatbot does not handle actual data, only text messages.

For your information, it is possible to show the image as markdown in the chatbot if it's a publicly accessible http url to the image, hypha actually support that. This need another service which will serve the image files, see here: https://ha.amun.ai/#/serverless-functions I don't have time to create an example for you now, but can be done.

yes, I think you can reuse the previous code, just not to return any actual np array to the chatbot.

**Comment by beniroquai** [comment]
Perfect. Thanks a lot!

**Pull request closed without merging**
