### PR TITLE
First commit after fork.

### PR DESCRIPTION
**Pull request by mgstingl**
Initial pull request.

### CODE REVIEW

**Comment by beniroquai** [comment]
Hey Thanks for reaching out! Would you mind filing the pull request against the labmaite branch I just created? Thank you! :-)

**Comment by mgstingl** [comment]
I edited the branch for the pull request to [openUC2:Labmaite]. Thanks!

**Comment by beniroquai** [comment]
Hey @mgstingl thanks for changing it. I went through it - roughly. Is there any chance you can include only those files from the stands stage that are really necessary? We can also create yet another repository for these files and include it as a submodule if necessary. We don't want 1000 header files ;-)

**Comment by mgstingl** [comment]
I don't know why it includes so many changes. Is there a way to exclude all files and then include a selected bunch? Please let me know how I should proceed :)

**Comment by beniroquai** [comment]
I must admit that I haven't checked which ifle is in use and which not. You can remove those you don't need and update the PR

**Comment by mgstingl** [comment]
I can´t find a way of doing it like that. Maybe I should create a new pull request and discard this one?

**Comment by beniroquai** [comment]
I think once your branch it will automatically mirror in the pr :)

**Comment by beniroquai** [comment]
I can try sorting things out. Would you mind to grant me access to you repo? 

image

**Comment by mgstingl** [comment]
Hi Benedict! I gave you access to the fork. Let me know if I need to do anything else.

**Comment by beniroquai** [comment]
Thanks! I pushed my first commit. Can you see the changes? I just
deleted files ;)

**Pull request merged**
